### ISSUE TITLE
Feature request: save animation to file

### ISSUE THREAD

**Issue by r-lyeh-archived** [kandebonfim/show-your-terms#7]
I dont know exactly the implications of this request, but it would be nice to have a final .gif (or any other animated image format). The animation would fit in any github README.md with an `[image]` tag.

**Comment by gasparfm** [comment]
I would be great. I think if we can draw it into a canvas (I think I saw a project to draw DOM objects with some styles, but I can't find it now), we could use something like https://github.com/eugeneware/gifencoder to create the animated gif.

But I think it should be ran at server side, and this would be an addon not to fatten the script.
